In [2]:
import numpy as np

In [3]:
list = [1,2,3]

In [5]:
arr = np.array(list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat) # 3x3 matrica jer ima po dve uglaste zagrade

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11,2) #generisanje matrica

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.linspace(0, 5, 10) #argumenti su pocetak, kraj i koliko elemenata izmedju start i stop, ali da su podjednako rasporedjeni, 1d matrica jer jedna zagrada

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.eye(4) #jedinicna matrica, matrica identiteta

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5) 

array([0.95799098, 0.1664679 , 0.01437585, 0.99899735, 0.50755444])

In [18]:
np.random.rand(5,5)
#.random.rand je uniformna raspodela brojeva

array([[0.37337619, 0.94709988, 0.44593957, 0.91106175, 0.16787796],
       [0.91092944, 0.9197014 , 0.17858889, 0.26757074, 0.43483401],
       [0.66145263, 0.61373542, 0.37661289, 0.11103993, 0.2655949 ],
       [0.25336036, 0.73089209, 0.61735937, 0.93321374, 0.21722556],
       [0.38422958, 0.10255705, 0.07741731, 0.36578558, 0.17603903]])

In [20]:
np.random.randn(4,4)
#.random.randn je normalna/Gausova raspodela

array([[ 0.13373514,  0.23399299, -0.44230911,  0.41116995],
       [-0.85974412, -0.85736978, -0.50014711,  0.71504751],
       [-0.60510248,  0.8045674 , -1.92266086,  0.93061321],
       [-1.29899551,  0.15118901,  0.55356898, -1.03484122]])

In [23]:
np.random.randint(1,100, 10)

array([ 6, 22, 19, 48, 64,  1, 36, 29, 49, 23])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50, 10)

In [27]:
ranarr

array([31, 25,  8,  8, 15, 30, 17, 45, 39, 47])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

47

In [30]:
ranarr.min()

8

In [32]:
ranarr.argmax()

9

In [33]:
ranarr.argmin()

2

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape

(5, 5)

In [40]:
arr.dtype

dtype('int32')

Numpy indexing and selection

In [41]:
arr = np.arange(0, 11)

In [42]:
arr[8]

8

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [46]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr[0:5] = 100

In [48]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0,11)

In [50]:
slice_of_arr = arr[0:6]

In [51]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[:] = 99

In [54]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr.copy()

In [57]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr_copy[:] = 100

In [61]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [62]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Ako se uzme slice nekog array-a(niza), i promene mu se vrednosti, onda ce i vrednosti iz cijeg je niza uzet slice da se promene
Pomocu .copy se pravi novi array koji je isti, ali ako mu se zamene vrednosti u slice, onda se originalni nece menjati

In [63]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [64]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [72]:
arr = np.arange(1,11)

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
bool_arr = arr > 5

In [76]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [77]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [78]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

Numpy operations

In [79]:
arr = np.arange(0,11)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
arr * 5 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [85]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [86]:
arr / arr

C:\Users\NOVAKJ~1\AppData\Local\Temp/ipykernel_7204/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])